#!/usr/bin/fish
# WARNING Do NOT edit this file by hand, as it was auto-generated from a bash alias, and may be overwritten in the future. please read {/home/amine/.config/fish/functions/bash-imports/README.md}

function gnuplot -d 'bash alias gnuplot import'
    rlwrap -a -c -b\"\\\"\\\"\\\'\\\'\" gnuplot $argv
end
